select * from customer

-- Q1: What is the total revenue generated by male vs. female customers?
select gender , sum(purchase_amount) as revenue
from customer 
group by gender
-- Male contributes more in total sales

-- Q2: Which customers used a discount but still spent more than the average purchase amount?
select customer_id , purchase_amount
from customer 
where discount_applied = 'Yes'
and purchase_amount > (select avg(purchase_amount) from customer)

-- Q3: Which are the top 5 products with the highest average review rating?
select top 5 item_purchased , ROUND(avg(review_rating),2) as avg_product_rating
from customer 
group by item_purchased
order by  avg(review_rating) desc

-- Q4: Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type , avg(purchase_amount) as avg_purchase_amount
from customer
where shipping_type in('Express' ,'Standard')
group by shipping_type

-- Q5: Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status, count(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_purchase,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue,avg_purchase desc

-- Q6: Which 5 products have the highest percentage of purchases with discounts applied?
-- discount rate per product
select TOP 5 item_purchased , 
ROUND( 100 * sum(case when discount_applied ='Yes' then 1 else 0 END) / count(*) ,2)AS percentage_purchase_with_discount
from customer
group by item_purchased
order by  percentage_purchase_with_discount DESC

-- Q7: Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with cte AS (
SELECT customer_id,
case when previous_purchases =1  then 'New'
     when previous_purchases between 2 and  10 then 'Returning'
     else 'Loyal'
END AS customer_segment
from customer)
select customer_segment , count(*) as number_of_customers
from cte
group by customer_segment
order by number_of_customers desc

-- Q8: What are the top 3 most purchased products within each category?
with cte2 as(
select  category, item_purchased, COUNT(*) as total_orders
from customer
group by category , item_purchased
), cte3 as(
select category, item_purchased  ,ROW_NUMBER() over (partition by category order by total_orders desc) as product_rank
from cte2
)
select category, item_purchased , product_rank
from cte3
where product_rank <= 3

-- Q9: Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select count(customer_id) as repeat_buyers , subscription_status
from customer
where previous_purchases >= 5
group by subscription_status

-- Q10: What is the revenue contribution of each age group?
select age_group , sum(purchase_amount) as total_revenue
from customer
group by age_group
order by  sum(purchase_amount) desc